name: github pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '13.2.0'

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Set env variables
              run: touch .env & echo -e "GOOGLE_MOBILE_ADS_APP_ID=${{ secrets.GOOGLE_MOBILE_ADS_APP_ID }}\nAD_MOB_UNIT_ID=${{ secrets.AD_MOB_UNIT_ID }}\nANDROID_CLIENT_ID=${{  secrets.ANDROID_CLIENT_ID }}\nANDROID_CLIENT_ID_WEB=${{  secrets.ANDROID_CLIENT_ID_WEB }}\nANDROID_STANDALONE_APP_CLIENT_ID=${{  secrets.ANDROID_STANDALONE_APP_CLIENT_ID }}\nGOOGLE_SIGN_IN_API_KEY=${{  secrets.GOOGLE_SIGN_IN_API_KEY }}\nAD_MOB_UNIT_ID_INTER==${{  secrets.AD_MOB_UNIT_ID_INTER }}" > .env

            - name: View variables
              run: cat .env
            - uses: expo/expo-github-action@v5
              with:
                  expo-version: 3.x
            - run: yarn install --frozen-lockfile
            - run: expo build:web
            - run: rm -rf node_modules/gh-pages/.cache
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  user_name: 'minecodebot'
                  user_email: 'minecode.geral@gmail.com'
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./web-build
