name: github pages

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '13.2.0'

            - name: Cache dependencies
              uses: actions/cache@v1
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-node-
            - name: Set env variables
              run: touch .env & echo -e "ADMOBUNITID=${{ secrets.ADMOBUNITID }}\nANDROIDCLIENTID=${{  secrets.ANDROIDCLIENTID }}\n ANDROIDCLIENTIDWEB=${{  secrets. ANDROIDCLIENTIDWEB }}\n ANDROIDSTANDALONEAPPCLIENTID=${{  secrets. ANDROIDSTANDALONEAPPCLIENTID }}\nGOOGLE_SIGNIN_APIKEY=${{  secrets.GOOGLE_SIGNIN_APIKEY }}" > .env
            - name: View variables
              run: cat .env 
            - uses: expo/expo-github-action@v5
              with:
                  expo-version: 3.x
            - run: yarn install --frozen-lockfile
            - run: expo build:web
            - run: rm -rf node_modules/gh-pages/.cache
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  user_name: 'minecodebot'
                  user_email: 'minecode.geral@gmail.com'
                  personal_token: ${{ secrets.PERSONAL_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./web-build
